from qutip import qsave, qload

from itertools import combinations
import os

from kitaev_network_analysis.physics.ground_state import get_ground_matrix


def partial_traces(hamiltonian, periodicity):
    """Compute all partial traces over n-2 sites.

    Having a 3 sites chain we'll get rho_ABC as a ground matrix.
    Then, we can compute the partial traces over rho_ABC and get:
    rho_AB, rho_BC and rho_AC.


    Important note about when periodicity is true:
        Since it is a close loop there are 2 symmetries:
         - (*)  Translational symmetry ptrace over pair (0, 1) is equal to pair: (1, 2), (2, 3), ... (n-2, n-1).
                   same happens for pair with distance 2 (0, 2): is equal to: (1, 3), (2, 4) ..., (n-3, n-1).
                   and we could continue with distance 3, 4, etc.
         - (**) Inverse symmetry ptrace over (0, 1) is equal to (0, n-1). Ex: (0, 2) = (0, n-2).

    Example:
        For a chain with num_sites = 3:
            - Periodicity = True --> [(0, 1)]
            - Periodicity = False --> [(0, 1), (0, 2), (1, 2)]

        For a chain with num_sites = 4:
            - Periodicity = True --> [(0, 1), (0, 2)]
            - Periodicity = False --> [(0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3)]
                Notice that with periodicity = True:
                    (0, 1) == (0, 3)(**) == (1, 2)(*) == (2, 3)(*)
                and
                    (0, 2) == (1, 3).

        For a chain with num_sites = 5:
            - Periodicity = True --> [(0, 1), (0, 2)]
            - Periodicity = False --> [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (1, 4), (2, 3), (2, 4), (3, 4)]
                Notice that with periodicity = True:
                    (0, 1) == (0, 4)(**) == (1, 2)(*) == (2, 3)(*) == (3, 4)(*)
                and
                    (0, 2) == (0, 3)(**) == (1, 3)(*) == (2, 4)(*) == (1, 4)(*)(**)

    Notice that we don't compute the transpose pair since (i, j) is equal to (j, i).

    Args:
        hamiltonian (FermionOperator): Describes the physics of the model.

    Returns:
        dict[(site_i, site_j): qutip.Qobj]: The dictionary has a key with the 2 sites that form the subsystem --> (site_i, site_j)
                                            and the value is partial trace which codifies the information about the subsystem.
    """
    ground_matrix = get_ground_matrix(hamiltonian)
    num_sites = len(ground_matrix.dims[0])

    if periodicity:
        pairs = [(0, site) for site in range(1, num_sites // 2 + 1)]
    else:
        pairs = combinations(range(num_sites), 2)

    return {pair: ground_matrix.ptrace(pair) for pair in pairs}


def save_partial_traces(ptraces, path):
    """It saves the ptraces that we have generated using the function: partial_traces()

    Args:
        ptraces dict[(site_i, site_j): qutip.Qobj]: Dictionary containing all the ptraces generated by partial_traces()
        path (pathlib.PosixPath): It stores the ptraces inside the path you have provided.
    """
    if not path.exists():
        path.mkdir(parents=True)
    for key, value in ptraces.items():
        qsave(value, os.fspath(path) + "/" + str(key))


def load_partial_traces(path):
    """Using the pathlib library you can write your path as:

    path = pathlib.Path(PACKAGE_PATH + "data/network_analysis/ptraces/" + configuration)
        PACKAGE_PATH = "/<your/path/to>/phase_transition_cna/"
        configuration = "13_1_2.0_0_True" (Any of the folders inside the folder: data/network_analysis/ptraces/)

    Args:
        path (pathlib.PosixPath): Path to an specific configuration in the ptraces folder.

    Returns:
        [dict of dicts]: A dictionary with all the values of mu and on each value of mu
                         there is a dictionary with all the partial traces.
    """
    ptraces_phase_transition = dict()

    for mu_dir in path.iterdir():
        ptraces_phase_transition[mu_dir.name] = dict()
        for ptraces in mu_dir.iterdir():
            ptraces_phase_transition[mu_dir.name][ptraces.stem] = qload(str(ptraces.parent / ptraces.stem))
    return ptraces_phase_transition
